package com.korealm.simbache.models;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "AuditLogs")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LogId")
    private Long logId;

    @ManyToOne(optional = false)
    @JoinColumn(name = "User_FK", nullable = false)
    private User user;

    @Column(name = "Action", nullable = false, length = 255)
    private String action;

    // SQL Server timestamp/rowversion: use byte[]; generated by DB
    @Column(name = "Timestamp", nullable = false, insertable = false, updatable = false)
    private byte[] timestamp;

    @Column(name = "Details", nullable = false, length = 2048)
    private String details;
}
